[package]
name = "idmage"
version = "0.1.0"
authors = ["rasviitanen <rasviitanen@gmail.com>"]

[dependencies]
rocket = "0.3.12"
rocket_codegen = "0.3.12"
svgmacro = "0.2.2"
textwrap = "0.9"
rand = "0.5.3"
rulinalg = "0.4.2"